code/datums/proximity_monitor/fields/player_collector.dm
code/game/machinery/electrical_jukebox.dm
tgui/packages/tgui-panel/audio/NowPlayingWidget.js
tgui/packages/tgui-panel/audio/middleware.js
tgui/packages/tgui-panel/audio/player.js
tgui/packages/tgui-panel/audio/reducer.js
tgui/packages/tgui/components/DraggableControl.js
tgui/packages/tgui/components/NumberInput.js

Jukebox playerına mute butonu ekler ve ayrıca farkında olduğum birkaç hatayı çözer.
Jukebox'ın sesini stop butonu ile kapattığınızda geri açmak isterseniz alandan çıkıp girmeniz geri girmeniz gerekiyordu bu saçma gereksinimi önlemek amacıyla mute butonu ekledim.
:cl:
add: Jukebox playerına mute butonu eklendi.
fix: Jukebox alanında sonradan girmeyip içerisinde doğanlar için ses çalacak.
fix: Jukebox alanındaki mobun clientı değiştiğinde yeni client için ses çalacak.
/:cl:

Electrical Jukebox Mute Seçeneği ve Bugfix

---

code/modules/research/anomaly/anomaly_core.dm

Anomaly core ile intihar ettikten sonra sinyal yollandığında oyuncu ölmüyor koddaki hata düzeltildi
bug fix
:cl:
fix: anomaly core ile intihar ederken sinyal yollandıktan sonra ölmeme sorunu çözüldü.
/:cl:

anomaly core suicide bug fix

---

code/datums/components/web_sound_player.dm

jukebox bazenleri şarkı bitmesine rağmen takılı kalıyordu
böyle yaptığımda düzeleceğini umuyorum
test etmedim çünkü sürekli olan bir şey de değil
bug fix
:cl:
fix: Jukebox şarkı bittiğinde takılı kalmayacak.
/:cl:

Jukebox Takılı Kalma

---

code/controllers/subsystem/explosions.dm
code/modules/power/supermatter/supermatter_delamination/delamination_effects.dm

devast range >1 oldugunda butun istasyonun isiklarinin kapalip acilmasi sinir bozucu, patlamalardan kaldirip sm'ye ekeldim
:cl:
del: ışıklar artık patlamalardan yanıp sönmeyecek (sm ve grav gen dahil değil)
/:cl:

Isik efektlerini patlamalardan kaldiriyor

---

_maps/map_files/Deltastation/AncientDeltaStation.dmm

Eski delta mapi üzerindeki sorunu gidererek surgery trayin eşyalı olarak spawnlanmasını sağlıyor.
Coroner artık eşyalarını oyun başı elde edebilecek.
:cl: genku
fix: Eski Delta'daki surgery tray dolu başlayacak
/:cl:

(Eski Delta) Surgery tray artık itemli şekilde spawnlanıyor

---

tgui/packages/tgui/interfaces/common/JobToIcon.ts

Brig Physicianın iconu font awasomede proya alındıgı icin gozukmuyordu.
Yeni hali bu
:cl:
fix: Latejoin Brig Physician iconu düzeltildi.
/:cl:

Fix - Brig Physician latejoin icon

---

_maps/map_files/Deltastation/AncientDeltaStation.dmm

Eski Delta İçin Atmosa huge air scrubber ekler.
Delta2 istasyonunda bulunuyor gerekli olabilir.
Eski Delta atmosa huge air scrubber ekler.
:cl:
add: Eski Delta Atmosa Huge Air Scrubber eklendi.
/:cl:

Eski Delta Huge Air

---

.github/workflows/mirror_bot.yml

upstream reposunda workflowlarda değişiklik yapıldığında github'ın verdiği token yetersiz kaldığından mirror workflowu bu değişikliği geçiremiyor.

Mirror workflow workflow yetkisi

---

code/modules/client/client_procs.dm
code/modules/discord/accountlink.dm

discord hesabını round içerisinde bağlayınca patreon contenti açılmıyordu onu düzeltir
hesaplarını bağlayanların yeni roundu beklememesi iyi olur
:cl:
fix: Discord hesabınızı bağladığınızda Patreon üyesiyseniz ayrıcalıkların uygulanması için sonraki roundu beklemeniz gerekmeyecek.
/:cl:

Patreon bug fix

---

tgui/packages/tgui/interfaces/PreferencesMenu/antagonists/antagonists/changelingmidround.ts

Midround changeling'i prefrences'a geri ekler
Olmamasını isteniyo bile olsaydı bu şekilde değil yalnızca dynamic.json ile halledilebilirdi.
:cl:
fix: Midround changeling antagonist tercihlerinde gözükecek.
/:cl:

Midround changeling'i prefrences'a geri ekler

---

code/__DEFINES/logging.dm
code/__HELPERS/logging/game.dm
code/controllers/configuration/entries/general.dm
code/datums/components/web_sound_player.dm
code/game/machinery/electrical_jukebox.dm
code/modules/logging/categories/log_category_game.dm
config/logging.txt

jukebox'ın admin log'unda olmaması gerek çünkü admin aksiyonu değil. jukebox'da şarkıya engel olma vs hala admin logunda ve component olan jukebox da admin logunda
doğru kategorizasyon
:cl:
admin: Jukebox'ın logu admin log yerine game log'da olucak
/:cl:

Jukebox log

---

code/controllers/configuration/entries/game_options.dm

Blue Alert uyarı mesajını tg wikisindeki standart operating procedures'a göre ayarlar
Oyuncuların birbiriyle daha fazla iletişime geçebilmesini sağlayacağını, shitsecliği biraz da olsa azaltacağını security - crew arası oluşan gereksiz escalationları azaltacağını ve bundan doğacak self antaglık durumlarını azaltacağını düşünüyorum. Wiki'de yazan alert kurallarının uygulanmasının daha doğru olduğunu düşünüyorum bu açıklama onun uygulanmasının önüne geçiyordu. Bazı command üyeleri secleri insanları zorla aramaya filan zorluyordu. Bu tarz tatsızlıkların önüne geçeceğini düşünüyorum. Her round insanları koridorda yürürken durduk yere baton yiyip çırıl çıplak soyulmalarını izliyorum. Rol kalitesini de düşürüyordu bu durum o yüzden böyle bir değişiklik yapmak istedim. 
:cl:
fix: Blue Alert …

Blue alert açıklama değişimi

---

code/datums/memory/key_memories.dm
code/modules/jobs/job_types/research_director.dm

Roundstart rdnin hafızasına law upload şifresini ekler
Rdnin bunu zaten istasyona gönderilmeden bilmesi gerektigini düsünüyorum. Aynı Cenin message monitor şifresini bilmesi gibi.
:cl:
qol: Research Director artık law upload şifresini ezbere biliyor.
/:cl:

RDnin hafızasına upload key eklenir.

---

_maps/shuttles/emergency_cami.dmm

scanner gatelerin spritelar directional olmuş bundan dolayı cami shuttledaki scanner gate ters görünüyordu
düzgün görünmesi daha iyi olur
:cl:
fix: Cami shuttleının kapısı düzgün görünecek
/:cl:

Cami shuttleının kapısının yönü

---

.github/workflows/mirror_bot.yml

bazenleri mirror yapınca configde önemli değişiklikler oluyor ve ben bunları gözden kaçırıyorum. bundan dolayı mirror prlarının açıklamasında bu önemli dosyalar değişiği zaman hatırlatıcı olması gözden kaçırmamı engelleyecektir.
reponun configi ile serverdakini olabildiğince senkron tutmak iyi olacaktır
oyuncuyu ilgilendirmez

Mirror bot için dosyaları takip etme hatırlatıcısı

---

code/modules/antagonists/heretic/knowledge/starting_lore.dm

Tgye neden böyle diye sordugumda rp acısından + secler yakaladıkları hereticlerin kalplerini değiştirip durdurabilsinler diyeymiş yani herhangi bir sorun cıkartmıcaktır diye düşünüyorum
Ipcler hereticlik yapamıyor, kötü olay.
önceden çözmüştüm sanıyodum ama çözmemişim
:cl:
fix: ipcler heretic kalbine sahip olabilecek
/:cl:

Ipc living heart fix

---

code/modules/client/preferences/species_features/ipc.dm

Bunu düzeltir: 
Normalde body_markinge çeviricektim ama body_marking hand iconunu değiştirmediği için doğru düzgün olmuyodu o yüzden etherealde çözdükleri gibi yaptım, 
bi ara ipcye feature updatesi atcağım zaman body_markinge çeviricem
Bu bir fix, insan olan bir kişi ipc chassisi görmek zorunda değil
:cl: Rengan
fix: Ipc chassisin Ipc olmayan ırklarda gözükmesi düzeltildi.
/:cl:

IPC chassis fix

---

code/game/machinery/computer/_computer.dm

1 noktada 2 bilgisayar olunca ve iconu computer olmayan bi bilgisayar locatelenince overlaylar bozuk oluyor.
Eskisi
Düzeltilmiş hali (normalde burasıda bozuk gözüküyodu duvardaki bilgiayardan dolayı)
Yakında bu connected computerleri tg eklicek ve o zaman buna gerek kalmıcak zaten ama genede fixlemek istedim
Fixler güzeldir.
:cl: Rengan
fix: Bir noktada 2 bilgisayar varken 2 bilgisayarın birleşme overlayı düzeltildi.
/:cl:

Connected computer fix

---

code/modules/mob/living/carbon/human/species_types/ipc.dm
code/modules/power/apc/apc_attack.dm
code/modules/surgery/organs/internal/cyberimp/augments_arms.dm
code/modules/surgery/organs/internal/stomach/stomach_ipc.dm

Create and destroyda toolset olan bir kol silinince toolsetten kolun referansı temizlenmediği için garbage hatası veriyor, bu pr onu düzeltir.
Tek tek hand variablesini weakref yapmak yerine böyle yapmak daha mantıklı geldi.
Ayrıca apcye şarj veremiyomuşuz onu da düzeltir.
IPCde power cord olmazsa şarj olmak için tek yol kalıyor, hoş değil.
:cl: Rengan
add: IPCye power cord tekrar eklendi.
fix: IPCnin apcye şarj verememe sorunu düzeltildi.
/:cl:

IPC power cord fix

---

code/datums/components/web_sound_player.dm
code/game/machinery/electrical_jukebox.dm

eskiden sadece youtube idi şimdi ise tam tersi malesef
yanlış yönlendirme
:cl:
fix: Jukebox'da yalnızca youtube oynatabildiği değil soundcloud oynatabildiği yazacak
/:cl:

"youtube only" yazısını "soundcloud only" olarak değiştirir
