psychonaut-station/PsychonautStation

code/modules/admin/chat_commands.dm, code/modules/discord/tgs_commands.dm
=> TGS Commands

code/__DEFINES/admin.dm, code/__DEFINES/span.dm, code/__HELPERS/type2type.dm, code/_globalvars/bitfields.dm, code/datums/components/admin_popup.dm, code/modules/admin/admin_ranks.dm, code/modules/admin/admin_verbs.dm, code/modules/admin/topic.dm, code/modules/admin/verbs/admin.dm, code/modules/admin/verbs/adminhelp.dm, code/modules/admin/verbs/adminpm.dm, code/modules/admin/verbs/commandreport.dm, code/modules/admin/verbs/debug.dm, code/modules/admin/view_variables/make_human.dm, code/modules/client/client_procs.dm, code/modules/interview/interview.dm, code/modules/requests/request_manager.dm, code/modules/tgui/states/admin.dm, config/admin_ranks.txt, config/admins.txt, config/config.txt, tgstation.dme, tgui/packages/tgui-panel/styles/tgchat/chat-dark.scss, tgui/packages/tgui-panel/styles/tgchat/chat-light.scss, tgui/packages/tgui/interfaces/Mentorhelp.tsx
- Refactors ticket system
- Adds new permission called "MENTOR"
- Adds new ticket type called _MENTOR
=> Add Mentorhelp verb

code/datums/components/on_hit_effect.dm, code/datums/elements/envenomable_casing.dm, code/modules/projectiles/guns/ballistic/bows/bow_arrows.dm
=> Fix arrows

code/modules/jobs/job_types/_job.dm, code/modules/mob/living/carbon/human/human.dm
Sentetik istasyona katıldığında geçilen duyuru sentetiğin yerine rastgele insan ismi belirtiyordu. Bu PR'da yapılan değişiklikler bu hatayı düzeltmektedir.
:cl:
fix: Sentetik istasyona katıldığında rastgele insan ismi yerine sentetiğin ismi duyurulacak.
/:cl:
=> Sentetik announcement

_maps/map_files/MiniStation/MiniStation.dmm, _maps/shuttles/arrival_mini.dmm, code/datums/shuttles.dm
🆑
add: Ministation özel shuttle'ı
add: Her tarafa holopadler eklendi
add: Kimya labratuvarına vial pixel artı eklendi
fix: Mapper kanalına atılan buglar düzeltildi
/🆑
=> ekler bu ministaton shuttle ve düzeltir

code/modules/experisci/experiment/experiments.dm, code/modules/experisci/experiment/types/scanning_plants.dm, code/modules/research/techweb/all_nodes.dm, tgstation.dme
Reverts psychonaut-station/PsychonautStation#68
=> Revert "Botany Experiments Changed"

code/modules/admin/verbs/individual_logging.dm
:cl:
fix: individual logging for LOOC
/:cl:
=> Add individual logging for LOOC

code/__DEFINES/keybinding.dm, code/__DEFINES/speech_channels.dm, code/datums/keybinding/client.dm, code/datums/keybinding/communication.dm, code/datums/keybinding/living.dm, code/modules/admin/verbs/adminhelp.dm, code/modules/tgui_input/say_modal/modal.dm, code/modules/tgui_input/say_modal/speech.dm, interface/skin.dmf, tgui/packages/tgui-say/ChannelIterator.test.ts, tgui/packages/tgui-say/ChannelIterator.ts, tgui/packages/tgui-say/styles/colors.scss, tgui/packages/tgui/interfaces/Mentorhelp.tsx, tgui/packages/tgui/interfaces/TicketSelectHelper.tsx, tgui/packages/tgui/styles/interfaces/TicketSelectHelper.scss, tgui/packages/tgui/styles/main.scss
Adds LOOC keybinds and reminds people that Mentorhelp exists.
Admins will do more work.
:cl:
add: LOOC keybind
qol: Ticket selector
/:cl:
=> LOOC Keybind & Ticket Selector

code/modules/projectiles/guns/energy/laser.dm
:cl:
fix: removed reskin from captain's Scattershot so captains scattershot will no longer be bugged
/:cl:
=> Captains Antique Gun Reskin Bug Fix

code/__DEFINES/rust_g_overrides.dm, code/controllers/subsystem/dbcore.dm, code/game/world.dm
fixes rust-g url_decode crash on reboot
=> Fix reboot crash

code/modules/jobs/job_types/brig_physician.dm
artık alet ile başlıyor
GIVES HIM TOOLS
GIVE EM TOOLS
=> Brig physician TOOLS

code/modules/mining/machine_redemption.dm
ORM upgrade
SAD MINERS
MORE ORES
=> ORM upgrade revival

code/datums/components/crafting/ranged_weapon.dm, code/modules/projectiles/ammunition/energy/laser.dm, code/modules/projectiles/guns/energy/crank_guns.dm, code/modules/projectiles/projectile/beams.dm, config/admins.txt
JUST LIKE THE FOUNDING FATHERS INTENDED
adminler için güzel bus itemi
:cl:
NAPOLYON TÜFEĞİ
/:cl:
=> yeni admin silahı

code/controllers/subsystem/explosions.dm, code/modules/power/gravitygenerator.dm, code/modules/power/lighting/light.dm
:cl:
add: Creaking lights
/:cl:
=> Creaking lights

code/modules/religion/religion_sects.dm, code/modules/religion/rites.dm, config/admins.txt
3 yeni sect ekliyor
Necromancy:ölü diriltiyor
Carp:balık çıkartıyor ve nedense yüzmeyi öğrensinler diye water vapor
Nature:podman yapıyor hayvan spawnlıyor
daha çeşitli sectler
:cl:
add: Nature sect
add :carp sect
add:Necromany sect
add:raise dead ritual
add:summon carp ritual
add:flood area ritual
add:summon animals ritual
add:create podperson ritual
add:convert into undead ritual
add:sacrifice living ritual
/:cl:
=> yeni sectler

code/game/machinery/computer/law.dm, code/modules/antagonists/traitor/objectives/final_objective/infect_ai.dm, code/modules/uplink/uplink_items/stealthy_tools.dm
:cl:
add: AI detector artik upload key'i gostericek
fix: Infect AI objektifi icin ai detector eklendi
/:cl:
=> Upload key tweaks

code/modules/power/gravitygenerator.dm
:cl:
fix: creak_lights triggered by derelict
/:cl:
=> Hotfix creaking lights

code/game/gamemodes/dynamic/dynamic_rulesets_midround.dm, code/modules/events/disease_outbreak.dm, code/modules/events/electrical_storm.dm, code/modules/events/ghost_role/abductor.dm, code/modules/events/ghost_role/alien_infestation.dm, code/modules/events/ghost_role/blob.dm, code/modules/events/ghost_role/changeling_event.dm, code/modules/events/ghost_role/nightmare.dm, code/modules/events/ghost_role/revenant_event.dm, code/modules/events/ghost_role/slaughter_event.dm, code/modules/events/ghost_role/space_dragon.dm, code/modules/events/ghost_role/space_ninja.dm
Random antag eventlerini kaldiriyor, cunku artik dynamic var.
Greenshiftleri koruyun
:cl:
del: Random antag eventleri kaldirildi
qol: Cogu midround antag icin enemy role araliklari arttirildi
/:cl:
=> Dynamic basini ezme pull requesti

.github/alternate_byond_versions.txt, .github/workflows/run_integration_tests.yml, code/__DEFINES/rust_g.dm, dependencies.sh
=> Revert rust-g back to 1.2.0

code/datums/components/crafting/weapon_ammo.dm
Holy arrow crafting tarifi
papazın okları çok hızlı bitiyor kendisi üretsin
:cl:
add: Holy arrow tarifi 10u holy water 5 wood 2 iron
/:cl:
=> Chaplain holy bow

code/controllers/configuration/configuration.dm, code/modules/unit_tests/chat_filter.dm, config/word_filter.toml
=> Match words on compile_filter_regex

code/datums/components/bakeable.dm
=> Fix oven glitch

_maps/RandomRuins/SpaceRuins/tgmc_ruin.dmm, _maps/shuttles/emergency_cami.dmm, code/game/turfs/closed/indestructible.dm
cami shuttle'ın duvarlarınıı indestructible yapar
tgmc ruinindeki cesedi kaldırıp yerine remain ekler ve dupe apcleri siler
^^
:cl:
balance: Cami shuttleının duvarları artık kırılamaz olucak.
fix: Tgmc ruinindeki duplicate apcler düzeltildi ve ceset remain ile değiştirildi.
/:cl:
=> cami shuttle ve tgmc ruini

code/modules/antagonists/changeling/changeling.dm, code/modules/antagonists/heretic/heretic_antag.dm, code/modules/antagonists/malf_ai/malf_ai.dm, code/modules/antagonists/space_ninja/space_ninja.dm, code/modules/antagonists/traitor/datum_traitor.dm, code/modules/antagonists/wizard/wizard.dm
antaglardan kendi görevini seçmeyi kaldırır
lowpop bait -loanselot
:cl:
del: Heretic, Changeling, Traitor, Wizard, Space Ninja, Malf AI iken kendi görevinizi seçemeyeceksiniz.
/:cl:
=> antaglardan kendi görevini seçmeyi kaldırır

code/modules/admin/IsBanned.dm, code/modules/admin/admin_verbs.dm
:cl:
admin: Set OOC Color artik butun yetkililer icin gecerli.
admin: Ticketlara butun yetkililer erisebilecek.
/:cl:
=> Adminlerin verblerini duzenler

_maps/map_files/MiniStation/MiniStation.dmm, _maps/shuttles/arrival_mini.dmm, code/datums/shuttles/arrival.dm
MiniStation'u daha oynanabilir kılmak.
:cl:
add: Arrival shuttle güncellendi. (by winstonbey)
fix: SM odasındaki üst üste binen emitterler düzeltildi.
/:cl:
=> MiniStation Duzeltmesi

code/modules/cargo/packs/security.dm
:cl:
balance: wt550 artik emagsiz kargo konsolunda yok
/:cl:
=> WT-550'i kargo'dan kaldirir

strings/tips.txt
:cl:
qol: 4-10 tipleri Türkçe'ye çevirildi.
/:cl:
=> tips.txt çeviri pt. 1

strings/tips.txt
:cl:
qol: 11-18 tipleri Türkçe'ye çevirildi.
/:cl:
=> tips.txt çeviri pt. 2

_maps/map_files/Deltastation/AncientDeltaStation.dmm
Eski Delta Station'a sec mechbay ekler.
:cl:
add: Eski Delta Station'a sec mechbay eklendi.
/:cl:
=> Security Mechbay

code/game/objects/items/rcd/RTD.dm
rtd ui'ında neon carpetlar düzgün gözükmüyordu
bug fix
:cl:
fix: RTD UI'ında neon carpetlar düzgün gözükecek
/:cl:
=> RTD Neon Carpet

code/modules/interview/interview.dm
:cl:
admin: Interviewlar artik tgs araciligi ile loglaniyor
/:cl:
=> Log interviews

html/changelogs/archive/2024-01.yml
=> Changelog fix

code/modules/assembly/bomb.dm
:cl:
balance: assembly bombalar artik bulky
/:cl:
=> kimsenin bilmedigi zamanlar daha komikti

code/game/world.dm, code/modules/mob/dead/dead.dm
:cl:
add: Players Ready artik normal oyunculara gorunur
fix: Hub zamani ve log zamanlari duzeltildi
/:cl:
=> Ince degisiklikler

code/controllers/subsystem/dynamic/dynamic_rulesets_roundstart.dm, tgui/packages/tgui/interfaces/PreferencesMenu/antagonists/antagonists/bloodbrother.ts
Blood brothers onceki kurallarin yanlis anlasilmasi nedeniyle kaldirilmisti, simdi geri eklendi
uplinksiz traitor
:cl:
add: Blood Brothers geri geldi
/:cl:
=> Blood Brothers

code/modules/jobs/job_types/_job.dm
:cl:
fix: configde random appearance flagi olmasina ragmen sadece isimleri randomize etme olayi fixlendi
/:cl:
=> force random appearance

_maps/map_files/Basketball/beach_bums.dmm, _maps/shuttles/emergency_cruise.dmm, _maps/shuttles/emergency_discoinferno.dmm, _maps/shuttles/emergency_rollerdome.dmm, _maps/virtual_domains/beach_bar.dmm, code/game/machinery/electrical_jukebox.dm
Hali hazirda old jukebox olan shuttle ve ghost spawn bolgelere public electrical jukebox eklendi
Old jukebox milletin oyununu kastiriyor ve 1 tane muzik var
:cl:
add: Public Jukebox: Beach Bum, Cruise ve Disco Inferno shuttlelarina herkesin kullanabilecegi jukebox eklendi
/:cl:
=> Public Jukebox

code/game/objects/items/tanks/tanks.dm
upstream tank rework ilk istenilen hedefi yapmadi, bu bombalar hala milleti gibleyip 4x4 breach acabiliyor
:cl:
balance: assemblybomb'lar tekrardan bulky
/:cl:
=> assemblybomb'lar tekrardan bulky

code/controllers/subsystem/dynamic/dynamic_rulesets_roundstart.dm
:cl:
fix: Animal artik blood brother olamayacak
/:cl:
=> Fix animal ruleset

.github/alternate_byond_versions.txt, .github/workflows/autowiki.yml, tools/autowiki/autowiki.js
wiki icin otomatik guncelleme/sema olusturma CI
=> Add autowiki

_maps/map_files/Deltastation/AncientDeltaStation.dmm
eski deltadaki odaları, kabloları, boruları düzenler
robotiğe mod core crate ekler
map sorunları
:cl:
fix: Eski Delta'daki kargo odaları düzeltildi.
fix: Robotiğine de MOD core crate eklendi.
/:cl:
=> eksi delta kargo

code/modules/antagonists/heretic/heretic_antag.dm
ascend olabilinecek
ascend olunmuyomuş
:cl:
fix: Hereticler tekrardan ascend olabilecek.
/:cl:
=> heretic ascend

code/controllers/configuration/entries/general.dm, code/modules/client/client_defines.dm, code/modules/discord/accountlink.dm, config/config.txt, tgui/packages/tgui/interfaces/DiscordVerification.tsx
discord verification ui'ı kötü gözüküyor. bot kısmını hallettiğime göre sıra bunda
türkçe mi yapsam bilemedim
<details><summary>Görseller</summary>
<p>
</p>
</details> 
tgui
:cl:
add: "Verify Discord Account" için tgui ekler
/:cl:
=> Verify Discord Account UI

.github/workflows/rerun_flaky_tests.yml
sikko sebeplerden hata veren testleri yeniden çalıştırcak
tgden farklı olarak issue oluşturmayacak
=> Rerun Flaky Tests

.github/PULL_REQUEST_TEMPLATE.md, .github/workflows/remove_guide_comments.yml
`PULL_REQUEST_TEMPLATE.md`'ye comment guide ekler ve pr açıldığında commentlerin silinmesi için workflow.
=> Pull Request Template

code/datums/mind/_mind.dm, code/game/machinery/computer/secretary_console.dm, code/game/objects/items/control_wand.dm, code/game/objects/items/devices/announcer_beacon.dm, code/modules/jobs/job_types/curator.dm, code/modules/jobs/job_types/nt_secretary.dm, code/modules/mapfluff/ruins/objects_and_mobs/sin_ruins.dm
Psychonaut özel rollerinde mind için kullanılan varlari siler ve onun yerine mindin assigned_role varını kullanir
Gerekli değil fakat kodu daha temiz yapiyor
Oyunda birşey değişmedi sadece gereksiz kod düzeltildi.
=> Mind Code improvements

README.md, code/controllers/configuration/entries/general.dm, code/modules/admin/verbs/adminhelp.dm, tgui/packages/tgui/interfaces/Changelog.jsx
psychonautstation.com'dan taşındık 🏚
=> Güncel Website URL'leri

strings/ion_laws.json
Spellcheck
Daha iyi Turkce
:cl: RengaN
spellcheck: "İskeletler" ile ilgili bir yazım hatası düzeltildi.
/:cl:
=> kucuk spellcheck

_maps/templates/holodeck_camping.dmm, code/modules/holodeck/holodeck_map_templates.dm
Yeni Holodeck mapi isterlerse sohbet isterlerse mangal yaparlar chill vakit geçirmek isteyenler için lazım olabilir. 
Mangal yapıp bira içip sohbet etmek isteyenler olursa low pop turlarında vakit geçirebilecekleri map.
İçinde mangal içki konserve gibi yemek barındıran orman tarzında bir holodeck.
:cl:
add: Orman temalı Holodeck map.
/:cl:
=> Yeni Holodeck Map.

code/modules/admin/chat_commands.dm, code/modules/discord/tgs_commands.dm
tidi ve mc komutunu ekler, check'i de bir tik duzenler
poly ve synthwl komutunu kaldirir
=> tgschat: tidi, mc

_maps/map_files/Deltastation/AncientDeltaStation.dmm
Eski deltada bulunan ai sat içerisindeki smese bağlı olan terminal atındaki kablo sorunu çözülür.
Ai sat sorununu fixler 30 dakika sonra şarj bitmez gibi.
Ai sat smes sorununu çözer.
:cl:
fix: Eski Delta'daki Ai Sat içerisindeki SMES'e bağlı olan terminal sorunu çözüldü.
/:cl:
=> Eski Delta Ai Sat Fix.

tgui/packages/tgui/interfaces/DiscordVerification.tsx
/verify komutunu sık sık yanlış yazıyolar. bunun için metini daha açıklayıcı olarak düzenledim
insanların daha az kafası karışır
:cl:
spellcheck: Discord verification menüsü daha açıklayıcı
/:cl:
=> discord verification menüsü daha açıklayıcı

_maps/map_files/Deltastation/AncientDeltaStation.dmm
Eski delta ai sat içerisinde hala elektrik kaynaklı sorunlar var delta2 ai sat sistemini eski deltaya geçirdim.
20 dakika içinde smes şarjı bitmez
:cl:
fix: Eski Delta ai sat elektrik sorununu çözer.
/:cl:
=> Eski delta ai sat fix

.github/workflows/mirror_bot.yml
her cuma tg update için otomasyon pr workflow
daha az üşenirim update atmak için (muhtemelen)
oyuncuları ilgilendirmiyor
=> Mirror bot workflow

code/modules/client/preferences.dm, code/modules/client/verbs/ooc.dm
Oyunda oldugumde artik farkli ghost iconu gormek istiyorum
:cl:
add: Artik OOC renginizi ve ghost formunuzu duzenleyebilirsiniz
/:cl:
=> Byond Member perklerini herkese acar

.github/workflows/mirror_bot.yml
açılan pr'ı draft yapar ve dosyalardaki conflict sayısını pr mesajına ekler
=> Mirror bot draft ve conflict sayısı

.github/workflows/mirror_bot.yml
3 saat ileride olduğumuzu unuttum
=> Mirror bot timezone

code/game/objects/items/robot/items/generic.dm, code/modules/jobs/job_types/animal.dm
animal mesleğinin playtime tracklenmemesini veve tgde değişen afterattack'dan dolayı çalışmayan kargo borgnunun emag eşyasını düzeltir
bug fix
:cl:
fix: Animal rolünün süresi artık takip edilecek
fix: Kargo borgunun emag eşyası çalışmaya devam edecek
/:cl:
=> animal playtime ve kargo borg

.github/workflows/mirror_bot.yml
bazi yazilari git terimlerine cevirdim, diff bot ban yememek icin de ignore taglarini mirror prlere ekledim
=> Mirror bot dokunuslari

code/modules/discord/accountlink.dm
emin olmamakla birlikte ui bundan dolayı çalışmıyo galiba (umarım)
bug fix
:cl:
fix: Verify Discord Account ekranı düzeltildi 
/:cl:
=> verify discord account ui fix

.github/workflows/mirror_bot.yml
conflict sayısı icon dosyalarında ve silinen dosyalarda 0 olması yerine daha açıklayıcı olur
$upstream_hash de yanlışmış onu düzelttim
=> mirror bot yanlış conflict sayısı ve upstrem ref

code/modules/client/client_procs.dm
byond 515.1641'den sonrasında datumlar için bracket indexing kullanılmıyor
bugfix
yok
=> bracket indexing

code/modules/client/preferences.dm
1 ay önce herkese açık yaptığımız byond member özelliklerini patreon üyelerine özel yapar
teşvik
:cl:
add: Artık OOC renk, ghost form vb. özellikler için Patreon üyesi olmanız gerekecek. Bununla beraber Patreon üyelerinin 8 karakter slotu olacak.
/:cl:
=> Patreon content

code/__DEFINES/tgs.dm, code/modules/tgs/README.md, code/modules/tgs/v5/api.dm
This pull request updates the TGS DMAPI to the latest version. Please note any changes that may be breaking or unimplemented in your codebase by checking what changes are in the definitions file: code/__DEFINES/tgs.dm before merging.
=> Automatic TGS DMAPI Update

code/modules/client/client_defines.dm, code/modules/client/client_procs.dm, code/modules/client/preferences.dm, code/modules/discord/accountlink.dm, code/modules/loadout/loadout_preference.dm, code/modules/patreon/loadout.dm
patreon şeyi ile ilgili hala sorun varmış umarım bu son olur ve sorun düzelir
bugfix
gerek yok bi önceki pr'ın devamı sayılır
=> tekrardan patreon bug fix (galiba)

code/modules/clothing/head/helmet.dm
Tactical helmete seclite takınca yok oluyodu onu düzelten bir pr.
Çünkü bu bir fix
:cl:
fix: Tactical helmete seclite takınca esyanın gozukmeme olayı fixlendi.
/:cl:
=> Tactical helmete seclite takınca yok olmasını fixleme prsi

code/__HELPERS/time.dm, code/game/world.dm, code/modules/events/_event.dm
uzun zaman önce time2text'i hatırlamadığım bir sebepten dolayı kodun bazı kısımlarında değiştirmişiz. bu günümüzde sorun yaratıyor ki özellikle her oyuna gir giriş yaptığında changelogu görmen gibi.
sunucuya her girdiğimde changelogu görmeye ihtiyacım yok
:cl:
fix: Changelog'da bir değişiklik olmadıkça oyuna her girdiğinizde changelog'u görmeyeceksiniz.
/:cl:
=> time2text'den kaynaklanan changelog sorunu

code/__HELPERS/time.dm, code/game/world.dm, code/modules/events/_event.dm
Reverts psychonaut-station/PsychonautStation#367
=> Revert "time2text'den kaynaklanan changelog sorunu"

code/game/world.dm
hub entrysindeki Discord kısmını diğer birçok serverdeki gibi üst satıra alır
hub entrysi yukardaki yerine aşşağıdaki gibi gözükse daha iyi olurdu
=> Hub entrysi Discord metni

README.md
:cl:
add: Github App eklendi (test)
/:cl:
=> Github App Test

.github/workflows/compile_changelogs.yml, .github/workflows/mirror_bot.yml, .github/workflows/update_tgs_dmapi.yml
https://api.github.com/users/psychonaut-ci[bot]/events/public
=> App UserID

code/modules/atmospherics/gasmixtures/gas_mixture.dm
vicirdek zamanı değişiklikler benim de haberin yok yani ama silmem laga sebep oldu galiba o yüzden geri alıyorum
atmos laglıyor
=> Atmos lagının gitmesine yardımcı olur umarım

code/modules/jobs/job_types/research_director.dm
upload_memoryi null olarak görüyordu
Bu bir fix
gerek yok 2 pr öncesi zaten
=> Rd memory fix

code/controllers/subsystem/dynamic/dynamic_rulesets_latejoin.dm
stowawayi koda geri eklediğimde brig physicianı hariç tutmayı unutmuşum
securityde antag olmaması gerek
:cl:
fix: Brig Physician kılığında kaçak yolcu olmadığı daha dikkatli kontrol edilecek.
/:cl:
=> Changeling brig physician

code/datums/world_topic.dm
=> href bug fix

tgui/packages/tgui/interfaces/PreferencesMenu/CharacterPreferences/JobsPage.tsx
fazlalık bir boş satır olması kötü gözüküyor
söyleyecektim aslında da söylemeyi unutmuşum
gerek yok
=> meslek açıklamalarından gereksiz boş satırı siler

code/modules/client/preferences/height.dm, tgstation.dme, tgui/packages/tgui/interfaces/PreferencesMenu/preferences/features/character_preferences/height.tsx
Kısa - Orta - Uzun olarak 3 farklı boy seçebiliyoruz.
Daha çok boy ayarı eklemememin sebebi; hem daha kısa olanlar daha çok hasar alıyor, hemde onların 2 tanesi quirk ile, 1 tanesi mutation ile alınabiliyor zaten. 
Eğer kişi maymunsa(roundstart olamıyor ama ne olur ne olmaz diye) boyunu seçemez.
Kişinin ırkı organik değilse (Örnek: plasmaman, IPC vs.) boyunu seçemez.
Kişide Settler veya Spacer quirki varsa(kendileri de boy ayarlıyor) kişi boyunu seçemez.
Herkesin boyunun (ne hikmetse) eşit olması saçma geliyor ve bence iyi birşeyde değil. O yüzden oynanışa etki etmeden boy ayarı eklemek istedim.
:cl: Rengan
add: Character Setup'a boy seçimi eklendi.
/:cl:
=> Character setupa boy ayarı ekler..

code/controllers/subsystem/credits.dm
normal insanlarda kalın, bunlarda değil ve kötü gözüküyor.
şuanki hali kötü gözüküyor
olmasın -sefa
=> Creditsde silicon ve ölülerin ckeyine kalın yazı ekler

code/game/objects/items/food/frozen.dm, code/game/objects/items/food/pastries.dm, code/game/objects/items/food/turkish.dm, code/modules/client/preferences/species_features/ipc.dm, code/modules/food_and_drinks/recipes/tablecraft/recipes_frozen.dm, code/modules/food_and_drinks/recipes/tablecraft/recipes_pastry.dm, code/modules/food_and_drinks/recipes/tablecraft/recipes_turkish.dm
Upstream mirror uni_icon testi
=> Mirror, foodtype ve uni_icon fixi

code/modules/client/preferences/height.dm
Karakterin görünümünü değiştiren şeylerin features kısmında olması daha iyi olucaktır.
:cl: Rengan
qol: Character setupdaki boy seçimi features kısmına alındı.
/:cl:
=> Height özelliğini secondary features kısmına alır

code/_onclick/hud/new_player.dm
:cl:
fix: ready sayisi tekrardan gorunuyor
/:cl:
=> Ready sayisini geri gosterir

code/__DEFINES/dcs/signals/signals_atom/signals_atom_main.dm, code/game/turfs/open/_open.dm, code/modules/mob/living/carbon/human/_species.dm, code/modules/mob/living/carbon/human/human.dm, code/modules/mob/living/carbon/human/species_types/ipc.dm, code/modules/reagents/chemistry/reagents/other_reagents.dm
COMSIG_ATOM_EXPOSED_WATER signalini kaldırdım
humanın wash procundan speciesdeki wash procu calısıyor artık
daha temiz kod
Oynanış olarak bişey değişmedi yani clye gerek yok sanırım
=> COMSIG_ATOM_EXPOSED_WATER signalini kaldırır

code/modules/religion/religion_sects.dm, code/modules/religion/rites.dm
necro-balance
Necromancer için dengeleme patchi
Necormancer secti ile çok pg yaptılar adminler şikayetci oldu denge çekicinin vakti geldi!
:cl:
del: Resurrect Ritesi kalktı
balance: Artık iskelet yerine zombi yapıyor sect
balance: Artık maymunlar 400 favor yerine 200 favor veriyor
balance: Artık organlar 10 favor yerine 30 favor veriyor
/:cl:
=> necromancer

code/modules/power/singularity/particle_accelerator/particle.dm, code/modules/power/singularity/singularity.dm
accelerated particle strengthi weak haric bufflar. yoksa asagıdaki gibi güc 2de olsa bile kacmıyo singulo
Önce tm olsa daha iyi olur
+ artık smle vs singularity yapılmaya çalışılmıyor çünkü gereksiz, o yüzden onları azcık buffladım böylece yapılması okadarda gereksiz olmaz.
Singulo suanki haliyle tehlikesiz ve bu durum singuloyu kötü yapıyor
:cl: Rengan
balance: Hızlandırılmış parçacıkların gücü arttırıldı.
balance: Smin oluşturduğu singularity artık daha çok elektrik üretiyor.
/:cl:
=> Önce TM - Hızlandırılmış parçaçık bufflandı

code/modules/admin/IsBanned.dm, code/modules/client/client_procs.dm
Suspicious logları discord a aktarır. Admin stuff
=> sus_log tgs

code/modules/admin/IsBanned.dm
shutdown sırasında birisi bağlanmaya çalıştığında runtime olmasını engeller
gerek yok
=> Shutdown Sırasında Gelen Connectionlar

code/datums/components/tactical.dm, code/game/objects/effects/effect_system/fluid_spread/effects_smoke.dm
Mob initlenmeden smokeye girerse veya çıkarsa bu hata cıkabiliyo 
crafting unit testinin gereksiz hata vermesini önler
gerek yok
=> unit test nametag fix

code/game/objects/items/storage/belt.dm
Kaptanın kılıcının gorunmezligini fixler
Gorunmez kılıc kötü
:cl: Rengan
fix: Kaptanın kılıcının görünmez olması düzeltildi.
/:cl:
=> Captain sabre fix

code/modules/client/preferences_savefile.dm
https://github.com/tgstation/tgstation/pull/93097 Mergelendi artık gerek kalmadı
geçen eklemiştim artık gerek yok
Oyuncuları ilgilendirmiyor
=> 2 kez sanitizeye gerek yok
